2024-09-15 23:36:34,438 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:36:40,086 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:36:45,733 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:36:51,065 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:36:56,719 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:02,364 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:08,009 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:13,657 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:19,301 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:24,948 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:30,594 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:36,238 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:41,884 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:47,531 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:53,178 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:37:58,824 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:04,470 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:10,116 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:15,462 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:20,792 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:25,966 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:31,296 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:36,947 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:42,278 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:47,926 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:53,572 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:38:59,220 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:04,868 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:10,200 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:15,846 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:21,491 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:27,153 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:32,488 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:37,820 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:43,466 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:49,119 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:39:54,770 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:00,419 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:05,592 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:11,242 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:16,572 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:22,225 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:27,873 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:33,046 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:38,376 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:43,706 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:48,888 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:53,536 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:40:59,186 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:04,829 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:10,004 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:15,650 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:21,297 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:26,471 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:32,117 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:37,763 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:43,093 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:48,738 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:41:54,384 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:00,031 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:05,678 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:11,008 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:16,181 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:21,827 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:27,470 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:33,115 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:38,762 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:43,937 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:49,112 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:54,758 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:42:59,931 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:05,261 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:10,908 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:16,081 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:21,725 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:27,371 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:32,545 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:38,192 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:43,838 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:43:49,169 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:02,475 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:02,480 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:08,125 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:08,126 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:13,768 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:13,769 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:19,099 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:19,100 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:24,426 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:24,428 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:30,071 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:30,072 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:35,715 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:35,717 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:41,360 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:41,361 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:47,003 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:47,004 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:52,648 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:52,650 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:45:58,299 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:45:58,300 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:03,945 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:03,946 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:09,275 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:09,277 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:14,947 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:14,948 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:20,592 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:20,594 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:26,235 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:26,236 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:31,882 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:31,883 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:37,525 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:37,527 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:43,172 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:43,173 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:48,815 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:48,816 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:54,458 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:54,459 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:46:59,634 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:46:59,635 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:04,967 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:04,968 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:10,613 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:10,615 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:16,268 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:16,269 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:21,912 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:21,914 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:27,558 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:27,560 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:33,233 - ERROR - An error occurred: Python int too large to convert to C long
2024-09-15 23:47:33,234 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 165, in <module>
    df = get_historical_klines(symbol, interval=60, limit=200)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 52, in get_historical_klines
    df['timestamp'] = df['timestamp'].astype(int)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C long

2024-09-15 23:47:39,446 - INFO - Indicators updated at 2024-09-15 22:47:38.808110
2024-09-15 23:47:39,447 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:47:39,447 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:47:44,448 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:47:44,449 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:47:49,450 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:47:49,450 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:47:54,451 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:47:54,452 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:47:59,453 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:47:59,453 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:04,455 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:04,455 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:09,456 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:09,457 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:14,458 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:14,458 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:19,459 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:19,460 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:24,461 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:24,462 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:29,463 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:29,463 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:34,464 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:34,465 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:39,466 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:39,467 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:44,469 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:44,469 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:49,471 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:49,471 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:54,472 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:54,473 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:48:59,474 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:48:59,475 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    positions = session.get_position(
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:49:04,476 - ERROR - An error occurred: 'HTTP' object has no attribute 'get_position'
2024-09-15 23:49:04,486 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 208, in <module>
    if last_log_time is None or (current_time - last_log_time).total_seconds() >= 600:
                                          ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 120, in get_current_position
    def get_current_position():
                    ^^^^^^^^^^^^
AttributeError: 'HTTP' object has no attribute 'get_position'

2024-09-15 23:49:08,200 - INFO - Indicators updated at 2024-09-15 22:49:07.256171
2024-09-15 23:49:08,200 - ERROR - An error occurred: Authenticated endpoints require keys.
2024-09-15 23:49:08,202 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 209, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 121, in get_current_position
    positions = session.get_positions(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_v5_position.py", line 22, in get_positions
    return self._submit_request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 236, in _submit_request
    signature = self._auth(
                ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 171, in _auth
    raise PermissionError("Authenticated endpoints require keys.")
PermissionError: Authenticated endpoints require keys.

2024-09-15 23:49:13,203 - ERROR - An error occurred: Authenticated endpoints require keys.
2024-09-15 23:49:13,203 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 209, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 121, in get_current_position
    positions = session.get_positions(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_v5_position.py", line 22, in get_positions
    return self._submit_request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 236, in _submit_request
    signature = self._auth(
                ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 171, in _auth
    raise PermissionError("Authenticated endpoints require keys.")
PermissionError: Authenticated endpoints require keys.

2024-09-15 23:49:18,205 - ERROR - An error occurred: Authenticated endpoints require keys.
2024-09-15 23:49:18,206 - ERROR - Traceback (most recent call last):
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 209, in <module>
    current_position, position_info = get_current_position()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\erik\OneDrive\Documents\bot2\SandsBot\main_loop.py", line 121, in get_current_position
    positions = session.get_positions(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_v5_position.py", line 22, in get_positions
    return self._submit_request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 236, in _submit_request
    signature = self._auth(
                ^^^^^^^^^^^
  File "C:\Users\erik\anaconda3\Lib\site-packages\pybit\_http_manager.py", line 171, in _auth
    raise PermissionError("Authenticated endpoints require keys.")
PermissionError: Authenticated endpoints require keys.

